server:
  port: 9098

spring:
  datasource:

    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.56.181.180:3306/workboard?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 120000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位毫秒
      time-between-eviction-runs-millis: 30000
      # 配置一个连接在池中最小生存时间
      min-evictable-idle-time-millis: 600000
      validation-query: SELECT 1 FROM sys_user
      test-while-idle: false # 关闭在连接空闲时进行连接有效性检查
      test-on-borrow: false
      test-on-return: false
      # 打开 PSCache，并且指定每个连接上 PSCache 的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的 Filter，去掉后监控界面 SQL 无法统计，wall 用于防火墙
      filters: stat,wall
      # 通过 connection-properties 属性打开 mergeSql 功能；慢 SQL 记录
      connection-properties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      # 配置 DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: .js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*
      # 配置 DruidStatViewServlet
      stat-view-servlet:
        url-pattern: /druid/*
        # IP 白名单，没有配置或者为空，则允许所有访问
        allow: 127.0.0.1
        # IP 黑名单，若白名单也存在，则优先使用
        deny: 192.168.31.253
        # 禁用 HTML 中 Reset All 按钮
        reset-enable: false
        # 登录用户名/密码
        login-username: root
        login-password: 123




ucode:
  code:
#     配置生成代码的路径
    package-name: cn.cestc
    use-swagger: true
    xml:
      add-xml: true
    controller:
      add-note-info: true
#MINIO
oss:
  name: minio
  accessKey: minio_access_key
  secretKey: minio_secret_key
  bucketName: iris
  endpoint: http://10.32.76.16:9000
  fileExt: txt,doc,docx,rtf,xlsx,csv

cestc:

  services:
    sso:
      domain: http://10.56.181.180
      port: 8889
      methods:
        userWithRole: userWithRole
    desktop:
      domain: http://10.56.181.180
      port: 8084
      methods:
        user: user
    template:
      domain: http://10.56.181.180
      port: 9097
      methods:
        createDoc: api/1/createPad
        saveDoc: api/1/setText
        getChar: api/1.2.7/getChatHistory
        deleteDoc: api/1/deletePad
        getDoc: api/1/getText
        docUrl: /p/
      apikey: 1aa1654245f6230c551b8314f39d10ffa0511a38774966b82a95fb99d5baf5ed

graceful-response:
  # 响应风格设置
  response-style: 1
  exclude-return-types: xin.altitude.cms.common.entity.AjaxResult