server:
  port: 9098

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.56.181.180:3306/workboard?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

ucode:
  code:
#     配置生成代码的路径
    package-name: cn.cestc
    use-swagger: true
    xml:
      add-xml: true
    controller:
      add-note-info: true
#MINIO
oss:
  name: minio
  accessKey: minio_access_key
  secretKey: minio_secret_key
  bucketName: iris
  endpoint: http://10.32.76.16:9000
  fileExt: txt,doc,docx,rtf,xlsx,csv

cestc:
  services:
    sso:
      domain: http://10.56.181.180
      port: 8889
      methods:
        userWithRole: userWithRole
    desktop:
      domain: http://10.56.181.180
      port: 8084
      methods:
        user: user

# 在线编辑板 请求url
template:
  apikey: apikey=04ef14e92789152399d8d9de2603ef4eb62d4766d3655abb99244b203fb77d23

  createDoc: http://10.56.181.180:9097/api/1/createPad?
  saveDoc: http://10.56.181.180:9097/api/1/setText?

  docUrl: http://10.56.181.180:9097/p/


